all: hw4 part4 part4b p3o

p3o: hw4old.cpp
	g++ hw4old.cpp -o p3

hw4: hw4.cpp
	g++ hw4.cpp -o hw4

part4: part4.cpp
	g++ part4.cpp -o p4

part4b: part4b.cpp
	g++ part4b.cpp -o p4b

clean:
	rm -f *.o hw4 p4 p3
