all: clean palindrome easyic fastic

palindrome: palindromecheck.cpp
	g++ palindromecheck.cpp -o palindrome

easyic:
	g++ easyinversioncount.cpp -o easyic

fastic:
	g++ fastinversioncount.cpp -o fastic

clean:
	rm -f *.o palindrome